config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/colonies/my_colonies/', to: 'colonies#show_my_colonies', as: :my_colonies
  get '/colonies/my_bookings/', to: 'bookings#show_my_bookings', as: :my_bookings
  delete '/colonies/:colony_id/bookings/:id', to: 'bookings#destroy', as: :destroy_booking

  resources :colonies do
    resources :bookings, only: [:new, :create]
    # get 'my_colonies', to: 'colonies#showmine'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :colony
end

app/models/colony.rb
class Colony < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :global_search,
                  against: [:name, :description, :location],
                  using: { tsearch: { prefix: true } }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :colonies
  # has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController


  def new
    @colony = Colony.find(params[:colony_id])
    @booking = Booking.new
  end

  def create
    @colony = Colony.find(params[:colony_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.colony = @colony
    # raise
    if @booking.save
      redirect_to my_bookings_path
    else
      render :new
    end
  end

  def destroy
    @colony = Colony.find(params[:colony_id])
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to my_bookings_path, notice: 'Booking has been successfully obliterated.'
  end

  def show_my_bookings
    @bookings = Booking.where(user: current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start, :end)
  end

end

app/controllers/colonies_controller.rb
class ColoniesController < ApplicationController
  before_action :set_colony, only: [:show, :edit, :update, :destroy]

  def new
    @colony = Colony.new
    @colony.user = current_user
  end

  def create
    @colony = Colony.new(colony_params)
    @colony.user = current_user
    if @colony.save
      redirect_to colony_path(@colony)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @colony.update(colony_params)
      redirect_to colony_path(@colony), notice: 'Colony was successfully updated.'
    else
      render :edit
    end
  end

  def index
    if params[:query].present?
      @colony_search = Colony.global_search( params[:query] )
      @colonies = @colony_search
    else
      puts "No results for your search. Here are other cool galaxies:"
      @colonies = Colony.all
    end
  end

  def show
    # @fake_year = @colony.created_at.year + @colony.created_at.min + 10000 - @colony.created_at.sec
    @booking = Booking.new
  end

  def show_my_colonies
    @colonies = Colony.where(user: current_user)
  end

  def destroy
    @colony.destroy
    redirect_to my_colonies_path, notice: 'Colony was successfully destroyed.'
  end

  private

  def set_colony
    @colony = Colony.find(params[:id])
  end

  def colony_params
    params.require(:colony).permit(:name, :location, :description, :population, :hostility, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def colony_fake_year(colony)
    # number_with_delimiter(colony.population, delimiter: ',')
    colony.created_at.year + colony.created_at.min + 10000 - colony.created_at.sec
  end

  def colony_hostility(colony)
    case colony.hostility
    when 0
      "garden of eden"
    when 1..20
      "utopia"
    when 21..40
      "low"
    when 41..60
      "OK"
    when 61..80
      "high"
    when 81..90
      "extreme"
    when 91..99
      "uninhabitable"
    else
      "certain death"
    end
  end

  def colony_owner_name(colony)
    colony.user.email.match(/^(?<username>.+)@/)[:username].capitalize!
  end

  def colony_population(colony)
    number_with_delimiter(colony.population, delimiter: ',')
  end

  def colony_photo(colony)
  end

  def colony_photo_url(colony)
    if colony.photo.attached?
      cloudinary_url(colony.photo.key)
    else
      'https://res.cloudinary.com/dqat8a2hi/image/upload/v1645788291/Space-BNB/wp1923649_ih89r9.jpg'
    end
  end

  def random_activities(count)
    activities = [
      {name: 'Hunting Ewoks',
      description: 'Shoot some ewoks',
      image_url:'https://mtv.mtvnimages.com/uri/mgid:file:http:shared:mtv.com/news/wp-content/uploads/2015/09/Ewok-1441395870.jpg?quality=.8&height=632.8089887640449&width=800'},

      {name: 'Getting mugged',
      description: 'How\'s your appetite to risk?',
      image_url:'https://livesafely.org/media/posts/123/avoid-being-mugged.jpg'},

      {name: 'Fishing in lake Quaglon',
      description: 'There\'s pleanty of fish in the sea',
      image_url:'https://imageio.forbes.com/specials-images/imageserve/615f7a84c4048b29616d55d6/A-person-fishing-from-a-boat-at-Islands-of-Loreto-/960x0.jpg?fit=bounds&format=jpg&width=960'},

      {name: 'Space Walks',
      description: 'Explore nearby asteroids and go space-drifting, tethered to a drone! fun AND dangerous!',
      image_url:'https://res.cloudinary.com/dqat8a2hi/image/upload/v1645620922/Space-BNB/banner_activities_jh28z5.jpg'},

      {name: 'Space Racing',
      description: 'Test your skills on the v-track in our specialised racing craft! full training provided. Thrilling!',
      image_url:'https://res.cloudinary.com/dqat8a2hi/image/upload/v1645621856/Space-BNB/outer-space-normandy-stars-planets-rings-spaceships-science-fiction-vehicles-wide-resolution-1080P-wallpaper-middle-size_whytac.jpg'},

      {name: 'GWWF Wrestling',
      description: 'Galactic Wookie Wrestling Federation - fancy yourself as a hard man? do you say \'whats your boggle mate?!\' prior to a bar fight? try your luck in the ring with a wrestling wookie. Life-Changing.',
      image_url:'https://res.cloudinary.com/dqat8a2hi/image/upload/v1645621997/Space-BNB/maxresdefault_xn4qy8.jpg'}
      ]

    activities.shuffle.first(count)
  end
end

app/views/bookings/new.html.erb
<div class="container-height">

  <div class="container">
    <%= render 'shared/booking_form' %>
  </div>
</div>

<%= render 'shared/footer'%>

app/views/bookings/show_my_bookings.html.erb
<div class="container-height">

<div class="colony-container">
  <div class="container">
  <!-- Explore -->
  <div class="banner-between text-center">
    <h2>My Bookings</h2>
    <svg class="svg-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M224 416c-8.188 0-16.38-3.125-22.62-9.375l-192-192c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L224 338.8l169.4-169.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-192 192C240.4 412.9 232.2 416 224 416z"/></svg>
  </div>

    <% @bookings.each do |booking| %>

    <div class="card-product" style="margin:10px 0;">

      <%= link_to (image_tag colony_photo_url(booking.colony)), colony_path(booking.colony) %>

      <div class="card-product-infos">
        <h2><%= link_to booking.colony.name, colony_path(booking.colony)%></h2>
        <p><strong>Check-in:</strong> <%= booking.start.nil? ? 'no date specified' : booking.start.strftime('%Y-%m-%d') %><br>
        <strong>Check-out: </strong> <%= booking.end.nil? ? 'no date specified' : booking.end.strftime('%Y-%m-%d') %><br>
      </div>
      <div style="float: right; margin-left: 50px;">
        <%= link_to "View", colony_path(booking.colony), class: 'btn btn-dark' %>

        <%= link_to "Cancel", destroy_booking_path(colony_id: booking.colony.id, id: booking.id), class: 'btn btn-dark', remote: true, method: :delete, data: {confirm: "Are you sure you want to cancel?"} %>

      </div>
    </div>
    <% end %>
  </div>
</div>

</div>
<%= render 'shared/footer'%>

app/views/colonies/edit.html.erb
<h2>Establish a colony</h2>
<div class="container">
  <%= simple_form_for(@colony) do |f| %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :location %>
      <%= f.input :population %>
      <%= f.input :hostility %>
      <%= f.input :description %>
      <%# f.input :photo as: :file %>
    </div>

    <div class="form-actions">
      <%= f.submit "Create!" %>
    </div>
  <% end %>

  <%= link_to 'Back to my colonies', my_colonies_path %>

</div>

app/views/colonies/index.html.erb
<div class="container">
  <div>
    <%= render 'shared/search'%>
  </div>

<!-- Explore -->
<div class="banner-between text-center">
  <h2>Explore Colonies</h2>
  <svg class="svg-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M224 416c-8.188 0-16.38-3.125-22.62-9.375l-192-192c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L224 338.8l169.4-169.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-192 192C240.4 412.9 232.2 416 224 416z"/></svg>
</div>

<div class="card-container">
  <% @colonies.each do |colony| %>

    <div class="card-trip">


      <%= image_tag colony_photo_url(colony) %>
        <%# cl_image_tag colony.photo.key %>

      <!-- <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" /> -->
      <div class="card-trip-infos">
        <div>
          <h2><%= link_to colony.name, colony_path(colony) %></h2>
          <p>created by <strong><%= colony_owner_name(colony) %></strong> in the year <%= colony_fake_year(colony) %></p>
          <p><%= colony.description %></p>
        </div>
        <h2 class="card-trip-pricing"><i style="width:1em; height:1em; background:url(https://res.cloudinary.com/dqat8a2hi/image/upload/v1645626818/Space-BNB/Dogecoin_Logo_myyf8i.png); background-size:cover; display:inline-block;"> </i> 500,000.00</h2>
        <img src="https://res.cloudinary.com/dqat8a2hi/image/upload/v1645622283/Space-BNB/terminator-portrait-paint-by-number_gbszfq.jpg" class="card-trip-user avatar-bordered" />
      </div>
    </div>

  <% end %>
</div>



  <div>
<!-- Explore -->
<div class="banner-between text-center">
  <h2>Explore Activities</h2>
  <svg class="svg-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M224 416c-8.188 0-16.38-3.125-22.62-9.375l-192-192c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L224 338.8l169.4-169.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-192 192C240.4 412.9 232.2 416 224 416z"/></svg>
</div>

  <% random_activities(4).each do |activity| %>
    <div class="card-product">
        <img src="<%= activity[:image_url] %>" />
        <div class="card-product-infos">
          <h2><%= activity[:name] %></h2>
          <p><%= activity[:description] %></p>
        </div>
    </div>
  <% end %>

  </div>
</div>

<%= render 'shared/footer'%>

app/views/colonies/new.html.erb
<!-- Explore -->
<div class="banner-between text-center">
  <h2>Establish a new Colony</h2>
  <svg class="svg-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M224 416c-8.188 0-16.38-3.125-22.62-9.375l-192-192c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L224 338.8l169.4-169.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-192 192C240.4 412.9 232.2 416 224 416z"/></svg>
</div>

<div class="container">
  <%= simple_form_for([ @colony ], remote: true ) do |f| %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :location %>
      <%= f.input :population %>
      <%= f.input :hostility %>
      <%= f.input :description %>
      <%= f.input :photo, as: :file %>
    </div>

    <div class="form-actions">
      <%= f.submit "Create!" %>
    </div>
  <% end %>

  <%= link_to 'Back to my colonies', my_colonies_path %>

</div>

app/views/colonies/show.html.erb
<div class="container-height">
<!-- Colony Details -->
<div class="banner-between text-center">
  <h2>Colony details</h2>
  <svg class="svg-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M224 416c-8.188 0-16.38-3.125-22.62-9.375l-192-192c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L224 338.8l169.4-169.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-192 192C240.4 412.9 232.2 416 224 416z"/></svg>
</div>

<!-- COLONY BANNER -->

<div class="colony-banner colony-show-banner text-center" style="background-image: linear-gradient(rgba(0,0,0,0.0),rgba(0,0,0,0.7)), url(<%= colony_photo_url(@colony) %>);">
  <div class="container">
    <h2><strong><%= @colony.name %></strong></h2>
    <p>Established by <strong><%= colony_owner_name(@colony) %></strong> in the year <%= colony_fake_year(@colony) %>. This colony is home to <strong><%= colony_population(@colony) %></strong> inhabitants with a <strong><%= colony_hostility(@colony) %></strong> hostility rating.</p>
  </div>
</div>

<div class="container">

<div class="row justify-content-between text-center m-3">
  <div class="col-3 stat-card">
      <h4><small>Founder</small></h4>
      <p><%= colony_owner_name(@colony) %></p>
  </div>

  <div class="col-3 stat-card">
    <h4><small>Established</small></h4>
    <p><%= colony_fake_year(@colony) %></p>
  </div>

  <div class="col-3 stat-card">
      <h4><small>Population</small></h4>
      <p><%= colony_population(@colony) %></p>
  </div>

  <div class="col-3 stat-card">
      <h4><small>Hostility</small></h4>
      <p>'<%= colony_hostility(@colony).capitalize! %>'</p>
  </div>
</div>

<div class="row justify-content-evenly text-left gx-1 m-3">
  <div class="col-12 stat-card">
      <h4 class="text-center sub-heading">Colony description</h4>
      <p style="margin: 0 auto"><%= @colony.description %></p>
  </div>
</div>

<div class="row justify-content-evenly text-center gx-1 m-3">
  <div class="col-12 stat-card">
  <!-- new booking form inline -->
  <%= render 'shared/booking_form' %>

  </div>
</div>


  <!-- Explore -->
<div class="banner-between text-center">
  <h2>Thrilling Activities Nearby</h2>
  <svg class="svg-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M224 416c-8.188 0-16.38-3.125-22.62-9.375l-192-192c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L224 338.8l169.4-169.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-192 192C240.4 412.9 232.2 416 224 416z"/></svg>
</div>


  <% random_activities(3).each do |activity| %>
    <div class="card-product">
        <img src="<%= activity[:image_url] %>" />
        <div class="card-product-infos">
          <h2><%= activity[:name] %></h2>
          <p><%= activity[:description] %></p>
        </div>
    </div>
  <% end %>



  </div>

</div>

<%= render 'shared/footer'%>

app/views/colonies/show_my_colonies.html.erb
<div class="container-height">
  <!-- Explore -->
  <div class="banner-between text-center">
    <h2>My Colonies</h2>
    <svg class="svg-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M224 416c-8.188 0-16.38-3.125-22.62-9.375l-192-192c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L224 338.8l169.4-169.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-192 192C240.4 412.9 232.2 416 224 416z"/></svg>
  </div>

  <div class="container">
    <%= link_to 'Establish a new Colony', new_colony_path, class: 'btn btn-dark' %>

    <% @colonies.each do |colony| %>

    <div class="card-product" style="margin:10px 0;">
      <%= link_to (image_tag colony_photo_url(colony)), colony_path(colony) %>

      <div class="card-product-infos">
        <h2><%= link_to colony.name, colony_path(colony) %></h2>
        <p><strong>Established:</strong> <%= colony_fake_year(colony) %><br>
        <strong>Population: </strong> <%= colony.population %><br>
        <strong>Hostility: </strong><%= colony.hostility %><br>
        <strong>Bookings: </strong><%= colony.bookings.count %></p>
      </div>
      <div style="float: right; margin-left: 50px;">
        <%= link_to "View", colony_path(colony), class: 'btn btn-dark' %>
        <%= link_to "Edit", edit_colony_path(colony), class: 'btn btn-dark' %>

        <%= link_to "Delete", colony_path(colony), class: 'btn btn-dark', remote: true, method: :delete, data: {confirm: "Are you sure you want to nuke this colony?"} %>

      </div>
    </div>
    <% end %>
  </div>
</div>

<%= render 'shared/footer'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Space BNB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- HERO BANNER -->
<div id="top" class="banner main-banner text-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dqat8a2hi/image/upload/v1645620922/Space-BNB/hero_image_e7g5yd.webp);">
  <div class="container">
    <h1><strong>S P A C E - B N B</strong></h1>
    <h2><em>Explore the Universe</em> like never before!</h2>
    <p>Book a stay in the galaxy and find amazing activities to enjoy.</p>
    <hr>
    <%= render 'shared/search' %>
  </div>
</div>

<!-- DISCOVER -->
<div class="banner-between text-center">
  <h2>DISCOVER</h2>
  <svg class="svg-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M224 416c-8.188 0-16.38-3.125-22.62-9.375l-192-192c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L224 338.8l169.4-169.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-192 192C240.4 412.9 232.2 416 224 416z"/></svg>
</div>

<!-- COLONIES BANNER -->

<div class="banner main-banner text-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dqat8a2hi/image/upload/v1645620922/Space-BNB/banner_colony2_afgrgv.png);">
  <div class="container">
    <h2>Book a stay at the <em>Best colonies</em></h2>
    <p>We bring you the largest selection of premium colonies <strong>galaxy-wide!</strong></p>
    <hr>
    <a href="/colonies/" class="btn btn-space-gradient btn-lg"><strong>Explore colonies</strong></a>
  </div>
</div>

<!-- ENJOY -->
<div class="banner-between text-center">
  <h2>ENJOY</h2>
  <svg class="svg-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M224 416c-8.188 0-16.38-3.125-22.62-9.375l-192-192c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L224 338.8l169.4-169.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-192 192C240.4 412.9 232.2 416 224 416z"/></svg>
</div>

<!-- ACTIVITIES BANNER -->

<div class="banner main-banner text-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dqat8a2hi/image/upload/v1645621320/Space-BNB/bnner_activities2_trvykq.jpg);">
  <div class="container">
    <h2>Live your <em>best life.</em> enjoy amazing activities!</h2>
    <p>Only boring people get bored. Find a range of <strong>exhilarating activities</strong> around the galaxy!</p>
    <hr>
    <a href="/colonies/" class="btn btn-space-gradient btn-lg"><strong>Explore activities</strong></a>
  </div>
</div>

<!-- SPACER -->
<div class="banner-between text-center">
  <a href="#top" class="undecorated">
  <svg class="svg-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M416 352c-8.188 0-16.38-3.125-22.62-9.375L224 173.3l-169.4 169.4c-12.5 12.5-32.75 12.5-45.25 0s-12.5-32.75 0-45.25l192-192c12.5-12.5 32.75-12.5 45.25 0l192 192c12.5 12.5 12.5 32.75 0 45.25C432.4 348.9 424.2 352 416 352z"/></svg>
  <p>Back to top</p>
  </a>
</div>

app/views/shared/_booking_form.html.erb
<%= simple_form_for [@colony, @booking] do |f| %>
<div class="row d-flex align-items-center">
  <div class="col-5">
<label for="booking_start">Start date:</label>
    <input type="date" name="booking[start]" id="booking_start" />
  </div>
  <div class="col-5">
<label for="booking_end">End date:</label>
    <input type="date" name="booking[end]" id="booking_end" />
  </div>
  <div class="col-2">
  <%= f.submit "Book now!", class: "btn btn-dark" %>
  </div>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    👾 Website produced by Aliens. We dunno how they did it, its magic.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon" style="background: #000;">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%# cl_image_tag("IMAGE_WITH_FACE_ID",width: 150, height: 150, crop: :thumb, gravity: :face) %>
      <div>
      <%= image_tag "logo.jpg" %>
      <span class="logo-type">S P A C E - B N B</span>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to "My Colonies [#{Colony.where(user: current_user).count}]", my_colonies_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "My Bookings [#{Booking.where(user: current_user).count}]", my_bookings_path, class: "nav-link" %></li>
          <li class="nav-item"><strong class="nav-link"><%= current_user.email.match(/^(?<username>.+)@/)[:username].upcase! %></strong></li>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dqat8a2hi/image/upload/v1645530508/Space-BNB/yuJKnlCNTN2sabHfSPhr_CyberPug_1-4_jcayx0.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Settings", "#", class: "dropdown-item" %>
              <%= link_to "Profile", "#", class: "dropdown-item" %>
              <%= link_to "Manage my Colonies", my_colonies_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%= simple_form_for :search, url: colonies_path, method: :get do |f| %>
  <div class="product-search">
      <div class="search-element">
        <label class="search-label">Where would you like to go?</label>
        <input class="search-input" type="text" autocomplete="on" placeholder="Galaxy Name" name="query">
      </div>
      <div class="search-element">
        <label class="search-label">Check in</label>
        <input class="search-input" type="date" placeholder="Choose Date" class="" autocomplete="on" name="date-in">
      </div>
      <div class="search-element">
        <label class="search-label">Check out</label>
        <input class="search-input" type="date" placeholder="Choose Date" class="" autocomplete="on" name="date-out">
      </div>
      <input type="submit" class="search-button">
  </div>

<% end %>